### PR TITLE
Iterative traversal method

### PR DESCRIPTION
**Pull request by goodyear-incaricotech**
Hi, i think that this will be useful to not having a bad recursive traversal method for trees.
I setup a common base for all tree classes and then i wrote the 4 traversal methods in the tree common base.
Most important, these traversal methods aren't in recursive mode, but iterative mode, and then they are (lazy) enumerable.

### CODE REVIEW

**Review by sephirothx — CHANGES_REQUESTED** [review]
Thanks, it looks very clean.
I would prefer not to expose the node classes as public. A possible fix could be to keep the `IBinarySearchTree<T>` and `IBinarySearchTreeNodeBase<TValue>` (renamed to `IBinarySearchTreeNode<T>` for consistency and with `internal` visibility), get rid of `BinarySearchTreeBase<TNode, TValue>` and implement general BST traversals with an internal `class BinarySearchTreeTraverser<TNode, TValue> where TNode: IBinarySearchTreeNode<TValue>` which can be a private field for the BSTs, and give the nodes implementation `internal` visibility.

**Comment by goodyear-incaricotech** [comment]
Thank you for the hints. I edited the code to unexpose the node classes, but without another internal classes BinarySearchTreeTraverser<TNode, TValue> (that eventually could be static but i like it even less).
To doing so, i setup in the tree base class with an
`private protected abstract IBinarySearchTreeNode<TValue> Root { get; }` that it is not exposed outside the assembly but children of tree base can see it and they must implement it trivially referring its own _root: like:
`private protected override IBinarySearchTreeNode<T> Root => _root;`

I put in the tree base class also min / max and index operator.

I hope it is helpful for you.

**Review by sephirothx — CHANGES_REQUESTED** [review]
Looks great, thank you very much.
Please make sure to revert all the changes to the file `DStruct.csproj` so i can merge

**Comment by goodyear-incaricotech** [comment]
Thank to you, so i can avoid an internal nupkg

**Review by sephirothx — APPROVED** [review]

**Pull request merged**
